wandb_version: 1

batch_size:
  desc: null
  value: 102
epsilon_decay:
  desc: null
  value: 0.818984274697315
learning_rate:
  desc: null
  value: 0.0017213148112733404
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717463421
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.7
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
